### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by alienscience** [supabase-community/svelte-kanban#2]
Hello,
  I tried out this example and it did not work for me in either Firefox or Chromium. Sign-in by magic link works, then when I click on a board, I get a blank page and the browser reports the following error (which I think is typescript related):

![svelte-trello-bug](https://user-images.githubusercontent.com/16070/158052565-de81e08d-c0ba-4603-963d-0f99e2e7b014.png)

**Comment by silentworks** [comment]
Please pull the latest updates to that branch or clone the repository again and try. I have updated the repository and its dependencies.
